xs-template: add template for error-handling between scripts

diff --git a/xs-template b/xs-template
--- a/xs-template
+++ b/xs-template
@@ -348,7 +348,7 @@ cat $tempfile.jobs | parallel -j+0 --progress
 ls time* 2> jjj  | grep ssp # send stderr to a file while piping stdout to another program
 [program] 1> out.txt 2> error.txt  # stdout to one file and stderr to another
 [program] 2>&1|tee logfile.txt # all output to both a logfile and screen
-echo "error" >&2  # send bash command to stderr: ">&2" literally means redirect the address of file descriptor 1 (stdout) to the address of file descriptor 2 (stderr) for that command1. Depending on how deeply you want to understand it, read this: http://wiki.bash-hackers.org/howto/redirection_tutorial
+echo "error" >&2  # send bash command to stderr: ">&2" literally means redirect to the address of file descriptor 2 (stderr) for that command1. Depending on how deeply you want to understand it, read this: http://wiki.bash-hackers.org/howto/redirection_tutorial
 (>&2 echo "error") # as above but to avoid interaction with other redirections use subshell
 # example: quiet list (suppress error message for ls)
 ls *bin 2>/dev/null
@@ -357,6 +357,14 @@ ls *bin 2>/dev/null
 # To get the stderr of cmd while leaving its stdout untouched
 # https://unix.stackexchange.com/questions/474177/how-to-redirect-stderr-in-a-variable-but-keep-stdout-in-the-console
 { err=$(cmd 2>&1 >&3 3>&-); } 3>&1
+
+# Managing error messages between scripts through redirection
+xs-prog2 data.txt 2> $tempfile".error"
+if [ -s $tempfile".error" ] ; then cat $tempfile".errro" >&2 ; exit ; fi
+	# ... code in xs-prog2...
+	if [ error condition ] ; then echo -e "\n--- Error ["$thisprog"]: error message here\n" >&2
+
+
 
 
 ################################################################################
